import { existsSync } from "node:fs";
import path from "node:path";
import dotenv from "dotenv";
import { describe, it } from "vitest";
import type { IHttpRequestHelper } from "n8n-workflow";
import { WatsonxOrchestrateApi } from "../../credentials/WatsonxOrchestrateApi.credentials";

type DebugHttpRequestOptions = {
  method?: string;
  url: string;
  headers?: Record<string, string>;
  body?: URLSearchParams;
};

function loadEnvForDebug(): void {
  const cwdEnv = path.resolve(process.cwd(), ".env");
  const repoEnv = path.resolve(__dirname, "..", "..", ".env");
  if (existsSync(cwdEnv)) {
    dotenv.config({ path: cwdEnv });
    return;
  }
  if (existsSync(repoEnv)) {
    dotenv.config({ path: repoEnv });
  }
}

function maskSecret(secret: string): string {
  const trimmed = secret.trim();
  if (!trimmed) return "<empty>";
  if (trimmed.length <= 12) return `${trimmed[0]}***${trimmed.slice(-1)}`;
  return `${trimmed.slice(0, 8)}...${trimmed.slice(-8)}`;
}

async function httpRequest(options: DebugHttpRequestOptions): Promise<unknown> {
  const res = await fetch(options.url, {
    method: options.method ?? "GET",
    headers: options.headers,
    body: options.body,
  });
  const text = await res.text();
  if (!res.ok) {
    throw new Error(`HTTP ${res.status} from ${options.url}: ${text.slice(0, 500)}`);
  }
  return JSON.parse(text) as unknown;
}

describe("debug auth header preview", () => {
  it("prints masked Authorization value generated by credential flow", async () => {
    loadEnvForDebug();

    const input =
      process.env.WXO_DEBUG_TOKEN_INPUT
      ?? process.env.WXO_TOKEN
      ?? process.env.WXO_API_KEY
      ?? "";

    if (!input.trim()) {
      console.log("Set one of: WXO_DEBUG_TOKEN_INPUT, WXO_TOKEN, or WXO_API_KEY");
      return;
    }

    const credential = new WatsonxOrchestrateApi();
    const helperContext = {
      helpers: { httpRequest },
    } as unknown as IHttpRequestHelper;

    const resolved = await credential.preAuthentication.call(helperContext, { token: input });
    const resolvedToken = String(resolved.resolvedAccessToken ?? "");
    const authorizationHeader = `Bearer ${resolvedToken}`;

    const inputKind = input.includes(".") ? "likely access token" : "likely API key";
    const resolvedKind = resolvedToken.split(".").length === 3 ? "JWT access token" : "non-JWT";

    console.log("---- Watsonx Orchestrate auth debug ----");
    console.log(`Input source kind: ${inputKind}`);
    console.log(`Input (masked): ${maskSecret(input)}`);
    console.log(`Resolved token kind: ${resolvedKind}`);
    console.log(`Resolved token (masked): ${maskSecret(resolvedToken)}`);
    console.log(`Authorization header (masked): Bearer ${maskSecret(resolvedToken)}`);
    console.log(`Authorization header length: ${authorizationHeader.length}`);
    console.log("---------------------------------------");
  });
});
